# Makefile for creatting an executable version of the Lolli intrepreter.
# Created by Josh Hodas (hodas@saul.cis.upenn.edu) 7/30/92

# The following line should give the name you use to invoke Standard ML of
# New Jersey.  Ideally the -noshare version (used in the build process for
# SML-NJ itself) should be used.

# for sun4_sparc
# SML = /usr/misc/.sml/bin/sml-noshare
# for alpha_osf1

SML = sml-cm

Lolli: ; $(SML) < make.sml

